openapi: 3.0.1
info:
  title: My API
  version: 1.0.0
paths:
  /pets:
    get:
      operationId: getPets
      responses:
        '200':
          $ref: '#/components/responses/ListPetsRes'
components:
  responses:
    ListPetsRes:
      description: ok
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  minimum: 1
                name:
                  type: string
                  example: Odie
